name: labels issues
on: 
   issues: 
       types: 
       - reopened
 jobs: 
    label_issues: 
    runs on: ubuntu-latest
    permissions: 
        issues: write
    steps: 
       - name: Label issues
         uses: andymackay/labeler@1.0.2
         with:
            add-labels: "trylabelme"
            repo-token: ${{ secrets.GITHUB_TOKEN }}
